### PR TITLE
add rbx-2.71828182

### PR DESCRIPTION
**Pull request by jasonkarns**
scraped via [ruby-build-update-defs](https://github.com/jasonkarns/ruby-build-update-defs) plugin

### CODE REVIEW

**Comment by hsbt** [comment]
:+1: Thanks!

**Comment by mislav** [comment]
Uhhh what version of rbx is that? Is it smaller or larger than rbx 2.8?

**Comment by hsbt** [comment]
It's larger than rbx 2.8

**Comment by jasonkarns** [comment]
According to this post
http://rubinius.com/2015/09/22/major-minor-maximize-delivering-features-minimize-trouble/
it was supposed to be the last 2.x release. I don't know if that ended up
being true or not.

**Pull request merged**
