### PR TITLE
Use shasum -a 256 instead of sha256sum in update-truffleruby

### PR DESCRIPTION
**Pull request by deepj**
@eregon ^^

### CODE REVIEW

**Comment by eregon** [comment]
Mmh, but this doesn't work on Linux:

```
$ shasum -a 256  README.md
zsh: shasum: command not found...
```
FWIW, the `ruby-versions` update script also expects `sha256sum` to be available:
https://github.com/postmodern/ruby-versions/blob/5f172745e188222d2f66da61141a825fb4eb42e3/update.sh#L73

**Comment by eregon** [comment]
Maybe using openssl is more portable, as shown in https://apple.stackexchange.com/a/230919/61281
That works on Linux (but the output is swapped, the digest is last).

**Comment by mislav** [comment]
See https://github.com/rbenv/ruby-build/blob/7205ae477579a279df2a041606398c79033d0fc8/bin/ruby-build#L221-L232

**Comment by deepj** [comment]
@mislav thanks for the tip! I’ll change it

**Comment by jasonkarns** [comment]
Starting to think the sha function from bin/ruby-build should be moved up into the lib() wrapper so that it can be leveraged by the CI tests, mirroring scripts, and scraper scripts. It's already duplicated once I believe, by the mirror script.

**Comment by mislav** [comment]
@jasonkarns That's not a bad idea! 👍

**Pull request closed without merging**
