### PR TITLE
Added 3.0.1, 2.7.3, 2.6.7, 2.5.9

### PR DESCRIPTION
**Pull request by Sixeight**
Ruby 3.0.1, 2.7.3, 2.6.7, 2.5.9 has been released.

https://www.ruby-lang.org/en/news/2021/04/05/ruby-3-0-1-released/
https://www.ruby-lang.org/en/news/2021/04/05/ruby-2-7-3-released/
https://www.ruby-lang.org/en/news/2021/04/05/ruby-2-6-7-released/
https://www.ruby-lang.org/en/news/2021/04/05/ruby-2-5-9-released/

### CODE REVIEW

**Review by olivierlacan — APPROVED** [review]
Verified the SHAs for new releases, looks good.

**Comment by olivierlacan** [comment]
@eregon Any chance you could merge this today since our Japanese friends might be fast asleep? Thank you. 🤗

**Review by eregon — APPROVED** [review]
Thanks!

**Comment by eregon** [comment]
Released as https://github.com/rbenv/ruby-build/releases/tag/v20210405

**Pull request merged**
