### PR TITLE
Upgrade to OpenSSL 1.1.1 (LTS)

### PR DESCRIPTION
**Pull request by deepj**
I upgraded all rubies depended on OpenSSL 1.1.0x to OpenSSL 1.1.1 (LTS). I tried to compile several rubies, and no problem occurred.

### CODE REVIEW

**Comment by deepj** [comment]
@hsbt there are any known problems with OpenSSL 1.1.1 from ruby-core side?

**Comment by hsbt** [comment]
I'm not sure that current stdlib fully supports OpenSSL 1.1.1 now. @rhe Can you confirm this?

**Comment by deepj** [comment]
@hsbt Hello, why https://github.com/rbenv/ruby-build/commit/62c391df5af391a519a1c53d07b1879d9ddf7fa2 or https://github.com/rbenv/ruby-build/commit/01fbd545adb4bce45da4fd494cc1e16331002a9e use OpenSSL 1.1.1?

**Comment by deepj** [comment]
@hsbt ^^

**Comment by hsbt** [comment]
> why [62c391d](https://github.com/rbenv/ruby-build/commit/62c391df5af391a519a1c53d07b1879d9ddf7fa2) or [01fbd54](https://github.com/rbenv/ruby-build/commit/01fbd545adb4bce45da4fd494cc1e16331002a9e) use OpenSSL 1.1.1?

There is no reason. I have no opinion about OpenSSL version.

**Comment by olivierlacan** [comment]
#1306 should be a good test of OpenSSL 1.1.1c if we merge it since it's just a 2.7.0-preview1 and won't impact too many people.

**Comment by olivierlacan** [comment]
@hsbt Is there anything other than `Net::HTTP` I can use to test OpenSSL 1.1.1? See: https://github.com/rbenv/ruby-build/pull/1306#issuecomment-497511754

**Comment by hsbt** [comment]
IMO, We should upgrade openssl-1.1.1 with Ruby 2.5+. Because Ruby 2.4 is security maintenance status. If we got an issue related to openssl-1.1.1, We couldn't fix it.

**Comment by mislav** [comment]
@eregon Is it okay to be bumping OpenSSL to 1.1.1 for truffleruby as well?

**Comment by eregon** [comment]
@mislav OpenSSL 1.1.1 should be fine for TruffleRuby as well (I use 1.1.1c locally, TruffleRuby uses the same OpenSSL C extension as MRI).

**Pull request closed without merging**
