### PR TITLE
Added definitions for Rubinius 3.61–3.69

### PR DESCRIPTION
**Pull request by boblail**
In the other definitions — for example —

```
install_package "rubinius-3.60" "https://rubinius-releases-rubinius-com.s3.amazonaws.com/rubinius-3.60.tar.bz2#39f83fc74216391af56ea1ad13372878c0ed41fae49ee6a8cf8b0369a54c3b57" rbx
```

is `39f83fc74216391af56ea1ad13372878c0ed41fae49ee6a8cf8b0369a54c3b57` the checksum?

How do I find or generate that?

### CODE REVIEW

**Comment by hsbt** [comment]
You can see it via https://rubinius-binaries-rubinius-com.s3.amazonaws.com/index.txt and https://rubinius-binaries-rubinius-com.s3.amazonaws.com/ubuntu/14.04/x86_64/rubinius-3.69.tar.bz2.sha512

**Comment by boblail** [comment]
Thanks @hsbt!

I have a follow-up question 😕. (Sorry — I'm new to this!)

The definition for rbx-3.60 says:

```ruby
install_package "rubinius-3.60" "https://rubinius-releases-rubinius-com.s3.amazonaws.com/rubinius-3.60.tar.bz2#39f83fc74216391af56ea1ad13372878c0ed41fae49ee6a8cf8b0369a54c3b57" rbx
```

The hash in the path is `39f83fc74216391af56ea1ad13372878c0ed41fae49ee6a8cf8b0369a54c3b57`

But the value of https://rubinius-releases-rubinius-com.s3.amazonaws.com/rubinius-3.60.tar.bz2.sha512 is `7aa606ca833bde488e1f0b353db4f46fda41152b5e26a63d1b7ec1ef89e9fcbeac3ee00f7ef938736e8778a27b56866e54bb9ddf67594e38046f616ba3e8835e`

Assuming the definition for rbx-3.60 is correct, what function should I pass the 128-character hash to to get the 64-character one out?

Thanks!

**Comment by eugeneius** [comment]
You can't transform a SHA-512 hash (128 characters) into a SHA-256 hash (64 characters) - they're created using different hash functions.

However, if you have the original file, you can compute both hashes from it. If the SHA-512 hash matches the one provided by Rubinius, then you know you have the correct SHA-256 hash too.

```bash
$ wget -q https://rubinius-releases-rubinius-com.s3.amazonaws.com/rubinius-3.60.tar.bz2 https://rubinius-releases-rubinius-com.s3.amazonaws.com/rubinius-3.60.tar.bz2.sha512
$ shasum -a 512 rubinius-3.60.tar.bz2
7aa606ca833bde488e1f0b353db4f46fda41152b5e26a63d1b7ec1ef89e9fcbeac3ee00f7ef938736e8778a27b56866e54bb9ddf67594e38046f616ba3e8835e  rubinius-3.60.tar.bz2
$ cat rubinius-3.60.tar.bz2.sha512
7aa606ca833bde488e1f0b353db4f46fda41152b5e26a63d1b7ec1ef89e9fcbeac3ee00f7ef938736e8778a27b56866e54bb9ddf67594e38046f616ba3e8835e
$ shasum -a 256 rubinius-3.60.tar.bz2
39f83fc74216391af56ea1ad13372878c0ed41fae49ee6a8cf8b0369a54c3b57  rubinius-3.60.tar.bz2
```

**Comment by hsbt** [comment]
Can you add sha256 digest to rubinius packages? Later, I will merge this pull request.

**Comment by ivanovaleksey** [comment]
Here are those checksums
```
rubinius-3.61 38623cf198b1b0047b4c3404070252903b4da33c091be8708c205815d1516636
rubinius-3.62 1cc468a7967687a062c11e21bf6787cc60f6894590eabe3fc9be5e9af36a022f
rubinius-3.63 3003298b9d53620ad84d71a63be2a37b53dfdfe6c2fced9280a7f3b219f365d4
rubinius-3.64 43e2efd91074b52dc1d691e1424dbbb2e91bc9406b595dbb4753e9dd6001eedb
rubinius-3.65 a4290b6cd1f332c90405bd421163658a2d91abf27c83ad3afe7dbbbd3628829a
rubinius-3.66 4bb237a1da1d52bc830bbe704bd4b995bbc07e50b558e460aff54d6bc309975e
rubinius-3.67 a5eedd6169f80df528ac73cf2ed9183e2f5a82a57ca0b2ae3962c26238427b87
rubinius-3.68 44f423a8557aa8fa383573638a94faaf3f9c587a771be267c60ed0c78784f567
rubinius-3.69 2dcde5cb7ba1e1664f6bf902cd866d2564985536a0908caeac2e4099b6b255b2
```

**Comment by boblail** [comment]
Thanks @ivanovaleksey!

@hsbt, I amended my commit and pushed it up with checksums.

**Pull request merged**
