### PR TITLE
`aria2c` doesn't support writing remote content to stdout

### PR DESCRIPTION
**Pull request by yyuu**
I've implemented `aria2c` support in #904. However, I finally realized that `aria2c` doesn't support writing remote content to stdout (https://github.com/aria2/aria2/issues/190).

I confirmed that basically this must be not a problem for ruby-build since it doesn't rely on `http get` without filename ([the only usage of http get](https://github.com/rbenv/ruby-build/blob/3304f96296c9912eaee27347e87e93a3e8fc5a29/bin/ruby-build#L412) is specifying its destination filename). It'd be better to be fixed though.

### CODE REVIEW

**Comment by mislav** [comment]
Thanks for catching this. Like my comment in https://github.com/rbenv/ruby-build/pull/904#issuecomment-221599563, I don't like that every tweak to aria2c support needs to touch all tests. Is there a way we can circumvent this? Maybe go back to stubbing `curl` instead, and `aria2c` as uninstalled on the system, and then have just 1 tests that stubs aria2c as supported and tests its invocation?

**Comment by yyuu** [comment]
It sounds nicer than current test impl..... I'll try to do it later.

**Comment by yyuu** [comment]
I've prepared test helper to remove `aria2c` from `$PATH`. Now we can use `curl` stub during test as same as before. I've prepared dedicated test case for `aria2c` and it'd be sufficient to check if `aria2c` is working.

@mislav could you review the changes again?

**Comment by mislav** [comment]
Thanks for doing all the work and being patient!

**Pull request merged**
