### PR TITLE
Use bump formula pr

### PR DESCRIPTION
**Pull request by hsbt**
To use official "pull-request" tool of homebrew

ref. https://github.com/rbenv/ruby-build/issues/980

### CODE REVIEW

**Comment by mislav** [comment]
Thanks! I've cut the script down a bit further in 073762c12869b323646f94ed6a6bfee6ccb289c2

**Comment by hsbt** [comment]
Thank you too!

**Comment by jasonkarns** [comment]
Just FYI, I extracted this script out to https://github.com/jasonkarns/brew-publish/blob/master/bin/brew-publish a while back (for nodenv-*)

It's been updated to use bump-formula-pr as well. Any desire to leverage this instead of having the script embedded directly? Would also be useful for rbenv and any other rbenv-* plugins that are included in homebrew.

**Comment by mislav** [comment]
> Any desire to leverage this instead of having the script embedded directly?

How would we leverage this vs. embedding? I like the embedding approach since it means that we don't have to pull in a 3rd party repo to gain access to a simple shell script.

**Comment by jasonkarns** [comment]
Seeing as there isn't a "standard" bash package manager, I would imagine git submodule or subtree are the only options. Since it would only be for maintainers of ruby-build, and not end users, I could see git-submodule being palatable, if barely. Personally, I think the better solution would be git-subtree. The file would be "embedded" in the repo without needing any extra commands to fetch. But at the same time, it could be trivially kept up to date with the "upstream" version of the script.

It could be used on all the rbenv repos in a consistent fashion, thus making all plugin releases consistent.

**Pull request merged**
