### PR TITLE
Add TruffleRuby 1.0.0-rc12

### PR DESCRIPTION
**Pull request by deepj**

### CODE REVIEW

**Comment by deepj** [comment]
Hm, the issue weird.

I could build it on macOS:

```
ruby-build truffleruby-1.0.0-rc12 ~/.rubies/truffleruby-1.0.0-rc12
ruby-build: use openssl from homebrew
Downloading truffleruby-1.0.0-rc12-macos-amd64.tar.gz...
-> https://github.com/oracle/truffleruby/releases/download/vm-1.0.0-rc12/truffleruby-1.0.0-rc12-macos-amd64.tar.gz
Installing truffleruby-1.0.0-rc12...
Using the precompiled OpenSSL C extension
TruffleRuby was successfully installed in ~/.rubies/truffleruby-1.0.0-rc12
Installed truffleruby-1.0.0-rc12 to ~/.rubies/truffleruby-1.0.0-rc12
```

**Comment by eregon** [comment]
Yes, I also have the same diff, and the sha256 digests seem correct and identical with https://github.com/postmodern/ruby-versions/pull/39
Maybe just a spurious failure?

**Comment by deepj** [comment]
I guess so

**Comment by eregon** [comment]
Can you close and reopen the PR to retrigger the CI? Otherwise I can try with another PR.

**Comment by deepj** [comment]
@deepj it's passed

**Comment by eregon** [comment]
@hsbt Could you merge this PR?

**Pull request merged**
