### PR TITLE
Upgrade to OpenSSL 1.0.2m and 1.1.0g

### PR DESCRIPTION
**Pull request by deepj**

### CODE REVIEW

**Comment by hsbt** [comment]
Thanks always!

**Comment by svoboda-jan** [comment]
Breaks all updated versions:

This:
```install_package "openssl-1.1.0f" "https://www.openssl.org/source/openssl-1.1.0g.tar.gz#de4d501267da39310905cb6dc8c6121f7a2cad45a7707f76df828fe1b85073af```

Must be:
```install_package "openssl-1.1.0g" "https://www.openssl.org/source/openssl-1.1.0g.tar.gz#de4d501267da39310905cb6dc8c6121f7a2cad45a7707f76df828fe1b85073af```

The OpenSSL version for `install_package` must be same as in the url.

**Comment by hsbt** [comment]
Fixed at https://github.com/rbenv/ruby-build/commit/b6892ea60d8f3e6e8612b3dc8ba0f0e07759afe7

**Comment by svoboda-jan** [comment]
The referenced commit does not fix all affected versions, like `2.3.5`.

**Pull request merged**
