### PR TITLE
shorter git command chains

### PR DESCRIPTION
**Pull request by eladeyal-intel**

### CODE REVIEW

**Comment by jasonkarns** [comment]
I like this! Do you know which was the first version of git that supported the `-C` option, so we know where we'd be dropping support?

**Comment by eladeyal-intel** [comment]
Git v1.8.5 2013 https://github.com/git/git/blob/master/Documentation/RelNotes/1.8.5.txt

**Comment by eladeyal-intel** [comment]
@jasonkarns

**Comment by jasonkarns** [comment]
Thanks @eladeyal-intel! I believe this is also has a secondary benefit of helping out Fish shell users who are running old versions of fish which don't support `&&`. 🚀

**Pull request merged**
