### PR TITLE
Add ruby 2.6.9, 2.7.5 and 3.0.3

### PR DESCRIPTION
**Pull request by casperisfine**
- https://www.ruby-lang.org/en/news/2021/11/24/ruby-2-6-9-released/
- https://www.ruby-lang.org/en/news/2021/11/24/ruby-2-7-5-released/
- https://www.ruby-lang.org/en/news/2021/11/24/ruby-3-0-3-released/

### CODE REVIEW

**Comment by casperisfine** [comment]
cc @hsbt @eregon

**Comment by seuros** [comment]
We should probably have a GitHub action that build this files once a release happen.

**Comment by eregon** [comment]
Thanks!

**Comment by flavorjones** [comment]
FYI: I get the following error when building 3.0.3 via ruby-build:

```

**Comment by flavorjones** [comment]
FYI, I get the following error when I build 3.0.3 via ruby-build:

```
$ rbenv install 3.0.3
Downloading ruby-3.0.3.tar.gz...
-> https://cache.ruby-lang.org/pub/ruby/3.0/ruby-3.0.3.tar.gz
Installing ruby-3.0.3...

BUILD FAILED (Linuxmint 20.2 using ruby-build 20211109-1-g678031b)

Inspect or clean up the working tree at /tmp/ruby-build.20211124131925.355557.B9z1l9
Results logged to /tmp/ruby-build.20211124131925.355557.log

Last 10 log lines:
linking shared-object ripper.so
make[2]: Leaving directory '/tmp/ruby-build.20211124131925.355557.B9z1l9/ruby-3.0.3/ext/ripper'
make[2]: Entering directory '/tmp/ruby-build.20211124131925.355557.B9z1l9/ruby-3.0.3'
./tool/file2lastrev.rb:6:in `require': cannot load such file -- optparse (LoadError)
	from ./tool/file2lastrev.rb:6:in `<main>'
make[2]: *** [uncommon.mk:1156: revision.tmp] Error 1
make[2]: Leaving directory '/tmp/ruby-build.20211124131925.355557.B9z1l9/ruby-3.0.3'
make[1]: *** [exts.mk:88: ruby] Error 2
make[1]: Leaving directory '/tmp/ruby-build.20211124131925.355557.B9z1l9/ruby-3.0.3'
make: *** [uncommon.mk:300: build-ext] Error 2
```

I can build from source fine on this machine. I'm running:

```
$ cat /etc/lsb-release 
DISTRIB_ID=LinuxMint
DISTRIB_RELEASE=20.2
DISTRIB_CODENAME=uma
DISTRIB_DESCRIPTION="Linux Mint 20.2 Uma"

$ cat /etc/upstream-release/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Ubuntu Focal Fossa"
```

I'm curious if anyone else is seeing similar breakage? If so I'd be happy to open a new issue.

**Comment by sterlzbd** [comment]
@flavorjones I'm seeing the same error building 2.7.5 on Ubuntu 18.04

```
vagrant@ubuntu-bionic:~$ rbenv install 2.7.5
Downloading ruby-2.7.5.tar.bz2...
-> https://cache.ruby-lang.org/pub/ruby/2.7/ruby-2.7.5.tar.bz2
Installing ruby-2.7.5...

BUILD FAILED (Ubuntu 18.04 using ruby-build 20211124)

Inspect or clean up the working tree at /tmp/ruby-build.20211124191353.18213.D9aLfu
Results logged to /tmp/ruby-build.20211124191353.18213.log

Last 10 log lines:
./tool/file2lastrev.rb:6:in `require': cannot load such file -- optparse (LoadError)
	from ./tool/file2lastrev.rb:6:in `<main>'
uncommon.mk:1130: recipe for target 'revision.tmp' failed
make[2]: *** [revision.tmp] Error 1
make[2]: Leaving directory '/tmp/ruby-build.20211124191353.18213.D9aLfu/ruby-2.7.5'
exts.mk:85: recipe for target 'ruby' failed
make[1]: *** [ruby] Error 2
make[1]: Leaving directory '/tmp/ruby-build.20211124191353.18213.D9aLfu/ruby-2.7.5'
uncommon.mk:295: recipe for target 'build-ext' failed
make: *** [build-ext] Error 2
vagrant@ubuntu-bionic:~$ cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.6 LTS"
```

**Comment by texpert** [comment]
asdf worked OK:

```
asdf plugin update ruby
asdf install ruby 2.7.5
```

**Comment by eregon** [comment]
I think those errors are best reported to https://bugs.ruby-lang.org/, it's very unlikely it would be due to `ruby-build`.

**Comment by hsbt** [comment]
They are already reported like https://github.com/rbenv/ruby-build/issues/1484

**Pull request merged**
