### PR TITLE
Upgrade to OpenSSL 1.0.2g

### PR DESCRIPTION
**Pull request by deepj**

### CODE REVIEW

**Comment by deepj** [comment]
Uf, it failed due to Rubinius 3.16. They probably changed the packaged so the checksum is invalid :(

**Comment by hsbt** [comment]
> They probably changed the package so the checksum is invalid now :(

:( Can you update its checksum?

**Comment by deepj** [comment]
@hsbt done :)

**Comment by deepj** [comment]
Hello, I apologize but can this PR be merged, please? /cc @mislav

**Pull request merged**
