### PR TITLE
Display the actual error when testing for Ruby's openssl extension

### PR DESCRIPTION
**Pull request by YellowApple**
I was encountering some build issues on MicroOS and needed the actual exception message in order to pinpoint a workaround.

### CODE REVIEW

**Comment by YellowApple** [comment]
(The specific error and workaround, in case anyone's curious: https://github.com/rvm/rvm/issues/3150#issuecomment-359323888)

**Review by mislav — COMMENTED** [review]
Hi, thank you for the contribution, but I do not believe that including the LoadError error message will meaningfully improve output for scenarios in which extensions failed to compile. In order to debug a failed extension, it's best to view the extension compilation log instead of just observing the error message. In the future, we might surface the locations of those logs better in ruby-build output, but for now, I'm opting to leave the LoadError output as-is.

**Comment by mislav** [comment]
> The problem is that the extension compiles "successfully", so there is no indication in the compilation log that something went wrong

That's a good point; thanks.

> Or could/should we reword `"The Ruby #{lib} extension was not compiled."` to be more accurate (e.g. `"There was a problem loading the Ruby #{lib} extension; make sure it compiled successfully."`)?

I like this idea! You are welcome to further amend your PR.

**Comment by YellowApple** [comment]
> I like this idea! You are welcome to further amend your PR.

Done :+1:

**Review by mislav — APPROVED** [review]
Thanks! After some deliberation, I've shortened the error message further. I plan to soon make an overhaul of this whole check process to make the output even clearer, but for now, I hope that the addition of the actual error message helps.

**Comment by YellowApple** [comment]
Looks good, thanks!

**Pull request merged**
