### PR TITLE
Update license year range to 2016

### PR DESCRIPTION
**Pull request by pra85**

### CODE REVIEW

**Comment by mislav** [comment]
Thanks for the suggestion, but there are several reasons why I won't accept this or any similar pull requests to my projects:

* I believe editing of the LICENSE file should be restricted to maintainers only.
* The end of year range in copyright notices is [only a formality and doesn't need to be strictly maintained](http://ben.balter.com/2015/06/03/copyright-notices-for-websites-and-open-source-projects/#so-what-date-should-you-use). If I make a release in the near future, I might bump up the year then.
* I find such contributions to be of very low value and therefore counter-productive to the project. It's very easy for maintainers to bump up a number when I want/need to. It's not easy to me, however, to sift through many GitHub notifications and pull requests at the start of each year and deal with such contributions to all the projects that I maintain.

**Comment by hubertlepicki** [comment]
"great" job @mislav. Way to encourage contributors. The PR is quite funny and does not really bring much value, that's true. But it's better if the LICENSE tells truth.

It'd be eve better if the LICENSE file was not having misleading message saying that the copyright is owned by one guy named Sam Stephenson, but said something like: "project maintainers and contributors", or gave full list of contributors (probably not possible unless you run some script to generate the lsit). You know, so it tells the truth.

**Comment by mislav** [comment]
I'd like to give more thanks to contributors somehow. For instance, the full and up-to-date list of contributors can [be seen here](https://github.com/rbenv/ruby-build/graphs/contributors) on GitHub.

The LICENSE file is not an appropriate place to list all the contributors since it should only list copyright owners, and currently the copyright owner is Sam because he has started this project. You should understand that a license is basically a formality— it lets people use and modify this as an open source project, and that's the only thing that's important. It doesn't really matter what the copyright line says.

**Comment by pra85** [comment]
@mislav I apologies that my pull request isn't useful. I was going through the developers listed in https://docs.google.com/spreadsheets/d/1oGsg02jS-PnlIMJ3OlWIOEmhtG-udTwuDz_vsQPBHKs/edit#gid=290603204 and manually checking if their repository had the license updated or not. If it wasn't, I would fork the repository and do a pull request for updating it.

Thanks for the advise about writing a bot for doing the same. I don't know how it done but I will surely try

Sorry once again if I offended you in some way

**Comment by mislav** [comment]
I'm not offended at all, @pra85. My advice is simply to use your free time to make more substantial contributions to open source projects that you use or are interested in. For example:

* good bug reports (with steps to reproduce) are awesome contributions,
* explaining how you had problems setting up the project in your own environment and suggestions how it could be better,
* documentation improvements,
* reviewing other people's pull requests,
* submitting your own pull request to fix a bug or add a feature.

**Comment by hubertlepicki** [comment]
@mislav I have to correct you because you are wrong in one thin I am afraid. But don't worry, not just you, it's a very common legal mistake.

"copyright owner is Sam because he has started this project"

This is *not* true. The copyright is collectively owned by all contributors, or more precisely: every contributor owns a copyright on the code he or she has contributed.

The only way to retain full copyright over code is to ask for signing contributor's agreement before merging in changes. This is, in fact, what some companies who license commercially their free software do.

Even if you sign appropriate legal clauses, the "author's copyright law" is in most jurisdictions not something you can sell at all. I.e. you are always remain author of given piece of code, no matter if you sold the rights to it to someone else or not.

**Comment by mislav** [comment]
> This is _not_ true. The copyright is collectively owned by all contributors, or more precisely: every contributor owns a copyright on the code he or she has contributed.

Thanks for correcting me. However, it doesn't seem widespread practice to update a LICENSE file with every new contributor's name?

**Pull request closed without merging**
