### PR TITLE
add --with-opt-dir configure option for FreeBSD.

### PR DESCRIPTION
**Pull request by yuichiro-naito**
It is necessary to install gems which has native library such as pg, mysql...

### CODE REVIEW

**Comment by yuichiro-naito** [comment]
Please merge this pull request.

**Comment by yuichiro-naito** [comment]
This is serious problem to me.

**Comment by znz** [comment]
How about `RUBY_CONFIGURE_OPTS=--with-opt-dir=/usr/local`?

**Comment by yuichiro-naito** [comment]
Thanks for the advise.
And I'm sorry that I couldn't reproduce this problem again.
I couldn't find what kind things have been changed in my environment.
Maybe I was something wrong.
I will close this Pull Request.

**Pull request closed without merging**
