### PR TITLE
Add definition for Ruby 2.7.2

### PR DESCRIPTION
**Pull request by koic**
Ruby 2.7.2 has been released.
https://www.ruby-lang.org//en/news/2020/10/02/ruby-2-7-2-released/

### CODE REVIEW

**Comment by attenzione** [comment]
Didn't check PR before, but created issue https://github.com/rbenv/ruby-build/issues/1478

**Comment by lunks** [comment]
Could a new version be issued for ruby-build with this change?

**Comment by hsbt** [comment]
The ruby core team have a plan to new release of Ruby 2.6 in this weekend. I will release the latest version of ruby-build after that.

**Comment by jeremiemv** [comment]
Thank you @hsbt 
Heroku has added support for 2.7.2 - things move so fast :)

**Pull request merged**
